"""empty message

Revision ID: 159a9ab6519c
Revises: a65b27bf4f58
Create Date: 2021-12-01 23:20:56.438124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159a9ab6519c'
down_revision = 'a65b27bf4f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_twitter_key', 'user', type_='unique')
    op.drop_column('user', 'twitter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_twitter_key', 'user', ['twitter'])
    # ### end Alembic commands ###
