"""empty message

Revision ID: a65b27bf4f58
Revises: 2807edd385a2
Create Date: 2021-12-01 23:18:44.878196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65b27bf4f58'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['twitter'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'twitter')
    # ### end Alembic commands ###
